### ISSUE TITLE
How to train from a pre-defined mesh?

### ISSUE THREAD

**Issue by DRosemei** [NVlabs/nvdiffrec#150]
Thanks for you great work! I want to know how to train an obj from a pre-defined mesh like bellow. Thanks in advance :)
![image](https://github.com/NVlabs/nvdiffrec/assets/27892562/3d63f94c-d580-4274-a6eb-a32158628847)

**Comment by jmunkberg** [comment]
Thanks @DRosemei ,

You can use the `"base_mesh"` option in the config to only run the second pass of the optimization. Additionally, if you specify `"lock_pos" : true ` the vertex positions will not be moved during the optimization. If you want some geometry optimization when using a pre-defined mesh as above, I would recommend a large Laplacian factor "laplace_scale" : 3000, so that the geometry movement is constrained.

This config is one example of using a pre-defined mesh: https://github.com/NVlabs/nvdiffrec/blob/main/configs/spot_metal.json

**Comment by DRosemei** [comment]
@jmunkberg Thanks for your kind help:)
