### ISSUE TITLE
About the bsdf

### ISSUE THREAD

**Issue by 07hyx06** [NVlabs/nvdiffrec#164]
Hi @jmunkberg, thanks for the code!!

After reading the code, I found that the implementation of BSDF in `render/renderutils/bsdf.py` is not used in the inverse rendering process. Did I miss something? Is it just for reference purposes? i.e. the implemented BSDF is corresponded to the split sum technique?

**Comment by JHnvidia** [comment]
Hello,

You are correct, these files are only reference / testing code. As you can see in the ops.py file,
https://github.com/NVlabs/nvdiffrec/blob/main/render/renderutils/ops.py#L379, each method in the `renderutils` package has a `use_python=False` parameter that you can use to fallback on the reference implementation. There's a CUDA optimized version of each method that's used by default for performance: https://github.com/NVlabs/nvdiffrec/blob/main/render/renderutils/c_src/bsdf.cu.

The bsdf file is leftover from an earlier project, https://github.com/NVlabs/nvdiffmodeling, for point lights only. If you're looking for the splitsum model it's somewhat unintuitively in the light.py file: https://github.com/NVlabs/nvdiffrec/blob/main/render/light.py#L85.

The code for computing the pre-filtered cubemaps for splitsum is here:
https://github.com/NVlabs/nvdiffrec/blob/main/render/renderutils/c_src/cubemap.cu. Unfortunately there is no python equivalent reference implementation because it would have been way too slow.

Regards,
Jon

**Comment by 07hyx06** [comment]
Thanks a lot!!
